/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author kabes
 */
public class MainFrame extends javax.swing.JFrame {
    
    private final JToolBar toolbar = new JToolBar();
    private final JButton btnAgregar = new JButton("Agregar");
//    private final JButton btnModificar= new JButton("Modificar");
//    private final JButton btnEliminar = new JButton("Eliminar");
//    private final JButton btnListar   = new JButton("Listar");
//    private final JButton btnBuscar   = new JButton("Buscar");

    private final PeliculaFormPanel formPanel = new PeliculaFormPanel();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        super("Gestión Cine Magenta");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(720, 460);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Toolbar (los no requeridos quedan deshabilitados/comentados)
        toolbar.add(btnAgregar);
//        toolbar.add(btnModificar);   btnModificar.setEnabled(false); btnModificar.setToolTipText("Disponible en la siguiente entrega");
//        toolbar.add(btnEliminar);    btnEliminar.setEnabled(false);  btnEliminar.setToolTipText("Disponible en la siguiente entrega");
//        toolbar.add(btnListar);      btnListar.setEnabled(false);    btnListar.setToolTipText("Disponible en la siguiente entrega");
//        toolbar.add(btnBuscar);      btnBuscar.setEnabled(false);    btnBuscar.setToolTipText("Disponible en la siguiente entrega");

        add(toolbar, BorderLayout.NORTH);
        add(formPanel, BorderLayout.CENTER);
    }
    
    public JButton getBtnAgregar()     { return btnAgregar; }
    public PeliculaFormPanel getFormPanel(){ return formPanel; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
