package view;

import model.Genero;

import javax.swing.*;
import java.awt.*;
import java.text.DecimalFormat;
import java.time.Year;
import javax.swing.border.EmptyBorder;

public class PeliculaFormPanel extends JPanel {

    private final JTextField txtTitulo = new JTextField();
    private final JTextField txtDirector = new JTextField();
    private final JSpinner spAnio;
    private final JSpinner spDuracion;
    private final JComboBox<String> cbGenero = new JComboBox<>(Genero.names());
    private final JButton btnGuardar = new JButton("Guardar");
    private final JButton btnLimpiar = new JButton("Limpiar");
    
    /**
     * Creates new form PeliculaJPanel
     */
    public PeliculaFormPanel() {
        setLayout(new BorderLayout(8,8));
        setBorder(new EmptyBorder(16, 18, 16, 18));

        int anioMax = Year.now().getValue() + 1;
        spAnio     = new JSpinner(new SpinnerNumberModel(2024, 1900, anioMax, 1));
        
        // quitar separador de miles y cualquier decimal
        JSpinner.NumberEditor edAnio = new JSpinner.NumberEditor(spAnio, "#"); // patrón entero
        spAnio.setEditor(edAnio);
        DecimalFormat f = edAnio.getFormat();
        f.setGroupingUsed(false);        // sin miles (ej. 2026, no 2,026)
        f.setMaximumFractionDigits(0);   // sin decimales
        
        spDuracion = new JSpinner(new SpinnerNumberModel(90, 1, 999, 1));

        JPanel form = new JPanel(new GridLayout(0,2,8,8));
        form.add(new JLabel("Título:")); form.add(txtTitulo);
        form.add(new JLabel("Director:")); form.add(txtDirector);
        form.add(new JLabel("Año:")); form.add(spAnio);
        form.add(new JLabel("Duración (min):")); form.add(spDuracion);
        form.add(new JLabel("Género:")); form.add(cbGenero);

        JPanel actions = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        actions.add(btnLimpiar);
        actions.add(btnGuardar);

        add(form, BorderLayout.CENTER);
        add(actions, BorderLayout.SOUTH);

        btnLimpiar.addActionListener(e -> clear());
    }
    
    public String getTitulo()   { return txtTitulo.getText().trim(); }
    public String getDirector() { return txtDirector.getText().trim(); }
    public int    getAnio()     { return (int) spAnio.getValue(); }
    public int    getDuracion() { return (int) spDuracion.getValue(); }
    public String getGenero()   { return (String) cbGenero.getSelectedItem(); }

    
    public JButton getBtnGuardar() { return btnGuardar; }

    public void clear() {
        txtTitulo.setText("");
        txtDirector.setText("");
        spAnio.setValue(2024);
        spDuracion.setValue(90);
        cbGenero.setSelectedIndex(0);
        txtTitulo.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
